version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shopping_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/shopping_db
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_
